### ISSUE TITLE
Error storing test results in BigQuery - 'str' object has no attribute 'database'

### ISSUE THREAD

**Issue by matthh9797jetty** [infinitelambda/dq-tools#33] opened 2024-10-07 12:00 UTC
### Describe the bug

When setting up the package exactly as described in the README for version ">=1.4.0", "<1.5.0" in BigQuery, DBT version v1.8. The following error appears when trying to run tests with the variable `dq_tools_enable_store_test_results` set to `true`. 

```
File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/adapters/bigquery/impl.py", line 244, in get_columns_in_relation
    database=relation.database, schema=relation.schema, identifier=relation.identifier

AttributeError: 'str' object has no attribute 'database'
```

### Steps to reproduce

Setup a DBT v1.8 project in Bigquery and run the setup instructions as specified in the README:

- Add to `packages.yml` file:

  ```yml
  packages:
    - package: infinitelambda/dq_tools
      version: [">=1.4.0", "<1.5.0"]
  ```

- Configure schema in `dbt_project.yml` file:

  ```yml
  vars:
    # (optional) to create db table in the schema named as AUDIT, default to `target.schema` if not specified
    dbt_dq_tool_schema: AUDIT
  ```

- Add on-run-end hook:

  ```yml
  on-run-end:
    - '{{ dq_tools.store_test_results(results) }}'
  ```

- Initialize `dq-tools` (new in v1.4+)

  ```bash
  dbt run -s dq_tools 
  ```

Then run the following:

```bash
dbt test --vars '{dq_tools_enable_store_test_results: true}'
```

### Expected results

DBT test results to be stored in the `dq_issue_log` table in BigQuery.

### Actual results

DBT generates the following error:

```
Command failed
'str' object has no attribute 'database'
```

### Screenshots and log output

Error message in DBT Cloud:
![image](https://github.com/user-attachments/assets/2f2545ff-081a-4751-80cc-b42199cf389e)

Vars and post hook in `dbt_project.yml`:
![image](https://github.com/user-attachments/assets/578e1950-e616-4033-b51c-165d2b76018e)

Full Error output Local:
![image](https://github.com/user-attachments/assets/7c6e610e-1e83-4b30-be41-c8ca6833047c)
![image](https://github.com/user-attachments/assets/0e2df0b4-7945-47e5-84d5-ac0f88930e86)
![image](https://github.com/user-attachments/assets/f0a84cde-54d6-43cc-b84c-f5b465740255)

### System information

**The contents of your `packages.yml` file:**

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: dbt-labs/codegen
    version: 0.12.1
  - package: calogica/dbt_expectations
    version: 0.10.0
  - package: infinitelambda/dq_tools
    version: [">=1.4.0", "<1.5.0"]
```

**Which database are you using dbt with?**

- [x] bigquery
- [ ] snowflake

**The output of `dbt --version`:**

```log
dbt Cloud CLI - 0.38.15 (56359b0505efe701ed8992da750ca7058fe41806 2024-09-25T13:26:28Z)
```

### Additional context
The database attribute of `relation.database`  doesn't look to exist in BigQuery which is causing an error in the `get_columns_in_relation` function.

### Are you interested in contributing the fix?

I'll do what I can to provide context

**Comment by il-dat** [comment] 2024-10-08 02:21
Thanks @matthh9797jetty Let me check it out 🏃

**Comment by il-dat** [comment] 2024-10-08 03:56
Hi @matthh9797jetty I found the issue, it should be caused by the Source Relation was returned as 'str' unexpectedly

It should be fixed in the above PR, and will be released as v1.7.0

Please help to try with v1.7 instead, we're going the deprecate `dbt_dq_tool_schema` variable, so please try to revisit the Readme again at the step using this variable, we will do this instead:
```
  models:
    dq_tools:
      # +database: DQ
      +schema: AUDIT
```

Thanks, let me know if there are further issues if any

**Closed** 2024-10-08 03:58 UTC
Labels: bug

**Comment by matthh9797jetty** [comment] 2024-10-08 09:24
@il-dat I can confirm that with version 1.7 everything is working as expected. Thank you for fixing and for the package - it is super useful. The only suggestion I would make is to bring the information about the `dq_tools_enable_store_test_results` variable a little higher up in the README as it looks like this variable is still required to store the tests?

**Comment by il-dat** [comment] 2024-10-08 09:32
> @il-dat I can confirm that with version 1.7 everything is working as expected. Thank you for fixing and for the package - it is super useful. The only suggestion I would make is to bring the information about the `dq_tools_enable_store_test_results` variable a little higher up in the README as it looks like this variable is still required to store the tests?

Great to know that it's working.

For your request, yes absolutely making sense, would you help to open a PR to update README file now? Thanks

**Comment by matthh9797jetty** [comment] 2024-10-08 10:14
@il-dat sure, I've opened a PR: [https://github.com/infinitelambda/dq-tools/pull/36](https://github.com/infinitelambda/dq-tools/pull/36)

**Comment by matthh9797jetty** [comment] 2024-10-09 14:01
@il-dat The initial fix was working on a certain select group of tests but now I've run it on my full data pipeline I am getting a similar error: `AttributeError: 'NoneType' object has no attribute 'database'`. Any idea what is causing this?

![image](https://github.com/user-attachments/assets/04881008-5234-47d3-969e-1fb4d105cef5)
![image](https://github.com/user-attachments/assets/265e8203-44f6-4c46-b981-afd6b26085c1)

**Comment by il-dat** [comment] 2024-10-10 08:37
> @il-dat The initial fix was working on a certain select group of tests but now I've run it on my full data pipeline I am getting a similar error: `AttributeError: 'NoneType' object has no attribute 'database'`. Any idea what is causing this?
> 
> ![image](https://private-user-images.githubusercontent.com/139125147/374990769-04881008-5234-47d3-969e-1fb4d105cef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDMxNzUsIm5iZiI6MTcyODU0Mjg3NSwicGF0aCI6Ii8xMzkxMjUxNDcvMzc0OTkwNzY5LTA0ODgxMDA4LTUyMzQtNDdkMy05NjllLTFmYjRkMTA1Y2VmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNjQ3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjE3YjU5NDAyMWYzZjQ0MTAyNzZhZmVmYmVlNTVjZmY3YTEzZTg2YmNlMGM4NTFkZWQ3ZDM0OTQ2MjUwNDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8K8crB8aYfw8HRGF9MmDXjcgKFgYys8KOsRxYSHWj1Y) ![image](https://private-user-images.githubusercontent.com/139125147/374990919-265e8203-44f6-4c46-b981-afd6b26085c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDMxNzUsIm5iZiI6MTcyODU0Mjg3NSwicGF0aCI6Ii8xMzkxMjUxNDcvMzc0OTkwOTE5LTI2NWU4MjAzLTQ0ZjYtNGM0Ni1iOTgxLWFmZDZiMjYwODVjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNjQ3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTQ4MzBjNjE4MzNhYzYxZmIxNzU3OWNmODczODQxZTE1ZWY1ZDUwZWUxNGRlODFkZGVhNmQ0ZTE5MzM4MGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Yosq1L4GW-SHrDRT3B5FFsiSN-eUMOKxMky337PSEfY)

Hey @matthh9797jetty Are you able to find the exact generic test that caused the issue? if not, can you send me your manifest.json and run_result.json into mail:dat@infinitelambda.com for deeper look? 

The error was saying that it could not find the model's Relation object based on the (generic) test result, which did not make sense.

Thanks

**Comment by matthh9797jetty** [comment] 2024-10-10 09:21
@il-dat I've been testing some combinations this morning and it looks like tests on `ephemeral` models are causing the issue - which would make sense of the error message. I can send you my manifest.json and run_results.json via email if that would help you to debug the issue?

**Comment by il-dat** [comment] 2024-10-10 10:04
> @il-dat I've been testing some combinations this morning and it looks like tests on `ephemeral` models are causing the issue - which would make sense of the error message. I can send you my manifest.json and run_results.json via email if that would help you to debug the issue?

Ah right, if it is the Ephemeral, this package would likely not support, can you try to test on the non-Ephemeral only?

Mainly because we need to row count stats to score the data quality

**Comment by matthh9797jetty** [comment] 2024-10-10 10:15
@il-dat For testing yes but I can't remove all the tests from ephemeral models in my production pipeline as they are an important part of verifying the intermediate logic and the `on-run-end` variable will error otherwise. Do you know anyway to get around this without removing all tests on ephemeral models?

**Comment by matthh9797jetty** [comment] 2024-10-10 13:56
@il-dat could you add a parameter to the store_test_results function so that it only runs on certain groups of models? For example:
```
{{ dq_tools.store_test_results(results, models=['marts/', 'staging/']) }}
```

**Comment by il-dat** [comment] 2024-10-11 01:48
> @il-dat For testing yes but I can't remove all the tests from ephemeral models in my production pipeline as they are an important part of verifying the intermediate logic and the `on-run-end` variable will error otherwise. Do you know anyway to get around this without removing all tests on ephemeral models?

This one, yes, I can exclude capturing test results of ephemeral models. Can you help to raise a feature request?

The workaround in the meantime, you can exclude them from your command:
```
dbt test --exclude config.materialized:ephemeral --vars '{dq_tools_enable_store_test_results: true}'
dbt test -s config.materialized:ephemeral
```

> @il-dat could you add a parameter to the store_test_results function so that it only runs on certain groups of models? For example:
> 
> ```
> {{ dq_tools.store_test_results(results, models=['marts', 'staging']) }}
> ```
Same idea as above for the workaround, and a new issue for the feature request.

I will try to tackle them soon. Thanks

**Comment by matthh9797jetty** [comment] 2024-10-11 08:45
@il-dat thanks! I can confirm that everything is working now that I have removed `dq_tools_enable_store_test_results = True` from my vars in `dbt_project.yml`. I now have one production job to build my pipeline `dbt build` and another to store the test results upon completion `dbt test --exclude config.materialized:ephemeral --vars '{dq_tools_enable_store_test_results: true}'`.

I can open a feature request but I think that the `dq_tools.store_test_results` function should ignore ephemeral models by default rather than accepting an argument, since these tests break the function. Do you think that seems sensible?

**Comment by il-dat** [comment] 2024-10-11 09:14
> I can open a feature request but I think that the `dq_tools.store_test_results` function should ignore ephemeral models by default rather than accepting an argument, since these tests break the function. Do you think that seems sensible?

Thanks @matthh9797jetty, yes please do, I'm not against this one, I will tackle it

My additional thinking now is that it would be better to use [Unit Testing](https://docs.getdbt.com/docs/build/unit-tests) to test your Ephemeral models instead? Since these ephemeral models are not the physical data, I will think about using Unit Test first.

**Comment by matthh9797jetty** [comment] 2024-10-11 12:32
@il-dat Yes, I think this would be a good use case for unit testing and at some point I may look at refactoring some of my tests on ephemeral models to use these instead. However, since unit tests were only introduced in dbt v1.8 and I think a lot of people will be using normal tests for ephemeral models and this feature would be good to have: [https://github.com/infinitelambda/dq-tools/issues/37](https://github.com/infinitelambda/dq-tools/issues/37)
